### ISSUE TITLE
Cube demo doesn't compile..

### ISSUE THREAD

**Issue by oscarbg** [Chabloom/VulkanOnMetal#1]
/VulkanOnMetal/src/cube/cube.c:1436:15: error: 
      expected expression
    filename =[[[NSBundle mainBundle] resourcePath] stringByAppendingPat...
              ^
so I commented 
 // filename =[[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent: @(filename)].UTF8String;
this 
and other similar line and after that I get:
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
so I tried to add below:
 
#elif defined(VK_USE_PLATFORM_IOS_MVK) || defined(VK_USE_PLATFORM_MACOS_MVK)
static void demo_mai..
this:
int main(int argc,char **argv)
{
    struct demo;
    void *view;
    demo_main(&demo,view);
}

but then compiles but running it got:
vkGetInstanceProcAddr failed to find vkGetPhysicalDeviceSurfaceSupportKHR

**Comment by bendiken** [comment]
I am stuck at the same problems attempting to make this build. For cleaner formatting:

    [ 97%] Linking CXX shared library ../lib/libVulkanOnMetal.dylib
    [ 97%] Built target VulkanOnMetal
    Scanning dependencies of target cube
    [ 98%] Building C object src/cube/CMakeFiles/cube.dir/cube.c.o
    VulkanOnMetal/src/cube/cube.c:1436:15: error: expected expression
        filename =[[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent: @(filename)].UTF8String;
                  ^
    VulkanOnMetal/src/cube/cube.c:1953:15: error: expected expression
        filename =[[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent: @(filename)].UTF8String;
                  ^
    2 errors generated.
    make[2]: *** [src/cube/CMakeFiles/cube.dir/cube.c.o] Error 1
    make[1]: *** [src/cube/CMakeFiles/cube.dir/all] Error 2
    make: *** [all] Error 2

@mdcasey Might you kindly consider adding a note to the README about the current status and whether people interested in this project should expect to be able to build and run the cube demo on some platform or another?

**Comment by mdcasey** [comment]
Sure. This is a work in progress and I didn't realize there was any real interest in it but I'll do that now. Thanks.

**Comment by bendiken** [comment]
I think there is and will be substantial interest in this project...

**Comment by mdcasey** [comment]
Alright. I'll get to work on it then.
