### ISSUE TITLE
Now that MoltenVK has been open-sourced, perhaps merge with them?

### ISSUE THREAD

**Issue by volkertb** [Chabloom/VulkanOnMetal#2]
Hi @mdcasey,

Not to dismiss your hard work on this project so far, but now that MoltenVK has been open-sourced, would it perhaps be better to combine all effort into that project instead?

Perhaps there's some stuff in VulkanOnMetal that MoltenVK could still benefit from?

https://github.com/KhronosGroup/MoltenVK

**Comment by mdcasey** [comment]
No that's actually something I had been thinking about. I think I'll archive this project and direct people to MoltenVK since it's free software now and serves the same purpose. Best to not duplicate work.
